version: "3"

services: 
    web:
        container_name: "backend"
        build: .
        ports: 
            - "3000:3000"
        depends_on: 
            - mongo

    
    mongo:
        container_name: mongo
        image: mongo:latest
        expose: 
            - "27017"
        ports: 
            - "27017:27017"       